import twilio from 'twilio';


const accountSid = "AC5ff006103982219a79017437f070dc32";
const authToken = "cdb7e522f54c8aa5fcbb64cebcac566e";
const client = twilio(accountSid, authToken);

async function sendSMS(){
    try {
        await client.messages
        .create({
           body: 'This is an autogenerated msg',
           from: '+12232505276',
           to: '+18728105534'
         })
         console.log("msg sent");
    } catch (error) {
        console.log(error);
    }
}
sendSMS()